- name: Sample Condition - when
  hosts: localhost
  become: true
  vars:
    fruit: true
    veg: false
  tasks:
    - name: print fruit
      ansible.builtin.debug:
        msg: fruit name is apple
      when: fruit is true
    - name: Print  Veg
      ansible.builtin.debug:
        msg: Veg name is carrot
      when: veg is true