- name: Sample Condition
  hosts: localhost
  become: true
  vars:
    fruit: true
    veg: false
  tasks:
    - name: print fruit
      ansible.builtin.debug:
        msg: fruit is apple
        when: "{{fruit}}"
    - name: Print  Veg
      ansible.builtin.debug:
        msg: Veg is carrot
        when: "{{Veg}}"