- name: Install apache service
  hosts: all
  become: true
  tasks:
    - name: Install apache service
      ansible.builtin.yum:
        name: httpd
        state: latest

- name: Install apache service using roles
    hosts: all
    become: true
      tasks:
        - sample









