- name: variables
  hosts: all
  vars:
    URL: pingtest.com
  become: true
  tasks:
    - name: variable printing
      ansible.builtin.debug:
        msg: URL = {{ URL }}

#####Ansible aAccess variables using double flower braces